// client/components/swagger-ui.jsx
import { useEffect } from 'react';
import SwaggerUI from 'swagger-ui';

import 'swagger-ui/dist/swagger-ui.css';

export default function SwaggerUIComponent() {
  useEffect( () => {
    SwaggerUI({
      dom_id: '#swagger-ui',
      queryConfigEnabled: true
    });
  }, [] );

  return ( <div id='swagger-ui'></div> );
}

// client/components/swagger-ui.vue
<script>
import { defineComponent } from 'vue';
import SwaggerUI from 'swagger-ui';

import 'swagger-ui/dist/swagger-ui.css';

export default defineComponent({
  mounted() {
    SwaggerUI({
      dom_id: '#swagger-ui',
      queryConfigEnabled: true
    });
  }
});
</script>

<template>
  <div id="swagger-ui"></div>
</template>
